name: Next.js Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev/**'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      # From https://github.com/r-lib/actions/tree/v2-branch/setup-r
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'

      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages: |
            any::renv

#      - name: Install R dependencies with renv
#        uses: r-lib/actions/setup-renv@v2
#        with:
#          cache-version: 1

      - name: Print GITHUB_TOKEN
        run: echo ${{ secrets.GITHUB_TOKEN }}

      - name: Print GITHUB_WORKSPACE
        run: echo ${GITHUB_WORKSPACE}

#      - name: Render and Publish
#        uses: quarto-dev/quarto-actions/publish@v2
#        with:
#          target: gh-pages
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: List outputs after quarto render
#        run: |
#          ls -l "${GITHUB_WORKSPACE}/_site"

      - name: Setup Node.js
        uses: ./.github/workflows/node.js

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - name: Build with Next.js
        run: npx next build

      - name: List outputs after next build
        run: |
          ls -l "${GITHUB_WORKSPACE}"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out
